{{- if not .Values.config.environment }}
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
data:
  gvpAddress: {{ required "Please provide the URL for the GV Platform + SCS system" .Values.config.gvpAddress }}
{{- end }}