{{- if .Values.ingress.enabled }}
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: "{{ .Release.Name }}-ingress"
  {{- if or .Values.annotations .Values.ingress.annotations }}
  annotations:
    {{- with .Values.annotations }}  
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  labels: 
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  rules:
  - http:
      paths:
      {{ if .Values.ingress.routePrefix }}
      - path: /{{ .Values.ingress.routePrefix }}/{{ .Values.ingress.path }}
      {{ else }}
      - path: /{{ .Values.ingress.path }}
      {{ end }}
        backend:
          serviceName: {{ .Release.Name }}-service
          servicePort: 80
{{- end }}