{{- if not .Values.secrets.api }}
apiVersion: v1
kind: Secret 
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
data:
  # Configuration values can be set as key-value properties
  gvpClientId: {{ required "Please provide a GV Platform client Id" .Values.secrets.gvpClientId | b64enc }}
  gvpClientSecret: {{ required "Please provide a GV Platform client Secret" .Values.secrets.gvpClientSecret | b64enc }}
---
{{- end }}
{{- if not .Values.secrets.databases }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
data:
  # Configuration values can be set as key-value properties
  scsMongoUrl: {{ required "Please provide SCS Mongo URL" .Values.secrets.scsMongoUrl | b64enc }}
{{- end }}
